version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.7.0
  helm: circleci/helm@1.2.0
  browser-tools: circleci/browser-tools@1.2.3

commands:
  checkout_and_decrypt:
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install git-crypt
      - run: echo "${GIT_CRYPT_KEY}" | base64 -d > git-crypt.key
      - run: git-crypt unlock git-crypt.key

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.5-browsers
        environment:
          DATABASE_URL: postgres://postgres@localhost/hmcts_common_platform_api_test
          RAILS_ENV: test
      - image: cimg/postgres:11.12
        environment:
          POSTGRES_DB: hmcts_common_platform_api_test
    steps:
      - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v12.19.1/node-v12.19.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.19.1-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v


      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - restore_cache:
          keys:
            - v1-yarn-{{ checksum "yarn.lock" }}
            - v1-yarn-

      - run:
          name: install bundle
          command: |
            gem install bundler -N

      - run:
          name: install dependencies
          command: |
            bundle check --path vendor/bundle || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Precompile Assets
          command: |
            yarn && bundle exec rails webpacker:compile

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - save_cache:
          paths:
            - node_modules
            - public/packs-test
          key: v1-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Database Setup
          command: |
            bundle exec rails db:migrate

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - run:
          name: run rubocop
          command: bundle exec rubocop

  install_on_cluster:
    executor: aws-eks/python
    steps:
      - checkout_and_decrypt
      - kubernetes/install-kubeconfig:
          kubeconfig: ENCODED_KUBECONFIG
      - kubernetes/install-kubectl
      - helm/install-helm-client:
          version: 'v3.5.4'
      - run:
          name: deny read-permission to group and others for ~/.kube/config
          command: chmod go-r ~/.kube/config
      - helm/upgrade-helm-chart:
          namespace: hmcts-mock-api-dev
          update-repositories: false
          chart: ./helm_deploy/hmcts-common-platform-mock-api
          release-name: hmcts-common-platform-mock-api
          values-to-override: image.tag=$CIRCLE_SHA1
          timeout: 10m

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          requires:
            - test
          repo: laa-crime-apps-team/hmcts-common-platform-mock-api
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master
      - install_on_cluster:
          requires:
          - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - master
