version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-eks: circleci/aws-eks@0.2.1
  kubernetes: circleci/kubernetes@0.7.0
  helm: circleci/helm@1.2.0
  browser-tools: circleci/browser-tools@1.2.3
  node: circleci/node@7.1.0

commands:
  checkout_and_decrypt:
    steps:
      - checkout
      - run: sudo apt-get update

jobs:
  test:
    docker:
      - image: cimg/ruby:3.3.6-browsers
        environment:
          DATABASE_URL: postgres://postgres@localhost/hmcts_common_platform_api_test
          RAILS_ENV: test
      - image: cimg/postgres:14.11
        environment:
          POSTGRES_DB: hmcts_common_platform_api_test
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '20.19'
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install bundle
          command: |
            gem install bundler -N

      - run:
          name: install dependencies
          command: |
            bundle check --path vendor/bundle || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Precompile Assets
          command: |
            export NODE_OPTIONS=--openssl-legacy-provider
            yarn && bundle exec rails assets:precompile

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - save_cache:
          paths:
            - node_modules
            - public/packs-test
          key: v1-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Database Setup
          command: |
            bundle exec rails db:migrate

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - run:
          name: run rubocop
          command: bundle exec rubocop

  build-and-push-app:
    machine:
      image: default
    steps:
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME
          region: $ECR_REGION
      - run: |
          aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
      - aws-ecr/build-and-push-image:
          repo: laa-crime-apps-team/hmcts-common-platform-mock-api
          tag: "${CIRCLE_SHA1}"
          extra-build-args: |
            --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) \
            --build-arg COMMIT_ID=${CIRCLE_SHA1} \
            --build-arg BUILD_TAG=${CIRCLE_SHA1} \
            --build-arg APP_BRANCH=${CIRCLE_BRANCH} \

  install_on_live_cluster:
    docker:
      - image: cimg/python:3.11.8
    steps:
      - checkout_and_decrypt
      - kubernetes/install-kubectl
      - helm/install-helm-client:
          version: 'v3.2.4'
      - run:
          name: Authenticate to LIVE cluster
          command: |
            echo -n ${CLUSTER_CERT_LIVE} | base64 -d > ./live_ca.crt
            kubectl config set-cluster ${CLUSTER_NAME_LIVE} --certificate-authority=./live_ca.crt --server=https://${CLUSTER_NAME_LIVE}
            kubectl config set-credentials circleci --token=${CIRCLE_CI_TOKEN_LIVE}
            kubectl config set-context ${CLUSTER_NAME_LIVE} --cluster=${CLUSTER_NAME_LIVE} --user=circleci --namespace=hmcts-mock-api-dev
            kubectl config use-context ${CLUSTER_NAME_LIVE}
            kubectl config current-context
            kubectl --namespace=hmcts-mock-api-dev
      - helm/upgrade-helm-chart:
          namespace: hmcts-mock-api-dev
          update-repositories: false
          chart: ./helm_deploy/hmcts-common-platform-mock-api
          release-name: hmcts-common-platform-mock-api
          values: ./helm_deploy/hmcts-common-platform-mock-api/values.yaml
          values-to-override: image.tag=$CIRCLE_SHA1

workflows:
  version: 2
  test_and_build_master:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - build-and-push-app:
          requires:
            - test
      - install_on_live_cluster:
          requires:
          - build-and-push-app

  test_and_build_branch:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
      - build-and-push-app:
          requires:
            - test
      - hold_install_on_live:
          type: approval
          requires:
            - build-and-push-app
      - install_on_live_cluster:
          requires:
          - hold_install_on_live
