version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-eks: circleci/aws-eks@0.2.1
  kubernetes: circleci/kubernetes@0.7.0
  helm: circleci/helm@1.2.0
  browser-tools: circleci/browser-tools@1.2.3
  node: circleci/node@7.1.0
  snyk: snyk/snyk@2.2.0
  court-data-end-to-end-tests: ministryofjustice/court-data-end-to-end-tests@volatile

executors:
  snyk-executor:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:3.4.4-browsers
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:circleci@127.0.0.1:5432/hmcts_mock
          TZ: Europe/London
      - image: cimg/postgres:17.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "circleci"
          POSTGRES_DB: hmcts_mock

commands:
  checkout_and_decrypt:
    steps:
      - checkout
      - run: sudo apt-get update

  build-temp-image:
    steps:
      - run:
          name: Compile Docker Image
          command: |
            docker build \
              --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) \
              --build-arg COMMIT_ID=${CIRCLE_SHA1} \
              --build-arg BUILD_TAG="app-${CIRCLE_SHA1}" \
              --build-arg APP_BRANCH=${CIRCLE_BRANCH} \
              --pull \
              --tag mock:scan \
              --file Dockerfile .

jobs:
  test:
    docker:
      - image: cimg/ruby:3.4.4-browsers
        environment:
          DATABASE_URL: postgres://postgres@localhost/hmcts_common_platform_api_test
          RAILS_ENV: test
      - image: cimg/postgres:17.4
        environment:
          POSTGRES_DB: hmcts_common_platform_api_test
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '20.19'
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install bundle
          command: |
            gem install bundler -N

      - run:
          name: install dependencies
          command: |
            bundle check --path vendor/bundle || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Precompile Assets
          command: |
            export NODE_OPTIONS=--openssl-legacy-provider
            yarn && bundle exec rails assets:precompile

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - save_cache:
          paths:
            - node_modules
            - public/packs-test
          key: v1-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Database Setup
          command: |
            bundle exec rails db:migrate

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - run:
          name: run rubocop
          command: bundle exec rubocop

  build-and-push-app:
    machine:
      image: default
    steps:
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME
          region: $ECR_REGION
      - run: |
          aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
      - run:
          name: Set env vars
          command: |
            [[ "$CIRCLE_BRANCH" == "main" ]] && ECR_TAGS="$CIRCLE_SHA1,latest" || ECR_TAGS="$CIRCLE_SHA1"
            echo "export ECR_TAGS=$ECR_TAGS" >> "$BASH_ENV"
            echo "export APP_BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z)"  >> "$BASH_ENV"
            source "$BASH_ENV"
      - aws-ecr/build-and-push-image:
          repo: laa-crime-apps-team/hmcts-common-platform-mock-api
          tag: "${ECR_TAGS}"
          extra-build-args: |
            --build-arg BUILD_DATE=$(APP_BUILD_DATE) \
            --build-arg COMMIT_ID=${CIRCLE_SHA1} \
            --build-arg BUILD_TAG=${CIRCLE_SHA1} \
            --build-arg APP_BRANCH=${CIRCLE_BRANCH} \

  install_on_live_cluster:
    docker:
      - image: cimg/python:3.11.8
    steps:
      - checkout_and_decrypt
      - kubernetes/install-kubectl
      - helm/install-helm-client:
          version: 'v3.2.4'
      - run:
          name: Authenticate to LIVE cluster
          command: |
            echo -n ${CLUSTER_CERT_LIVE} | base64 -d > ./live_ca.crt
            kubectl config set-cluster ${CLUSTER_NAME_LIVE} --certificate-authority=./live_ca.crt --server=https://${CLUSTER_NAME_LIVE}
            kubectl config set-credentials circleci --token=${CIRCLE_CI_TOKEN_LIVE}
            kubectl config set-context ${CLUSTER_NAME_LIVE} --cluster=${CLUSTER_NAME_LIVE} --user=circleci --namespace=hmcts-mock-api-dev
            kubectl config use-context ${CLUSTER_NAME_LIVE}
            kubectl config current-context
            kubectl --namespace=hmcts-mock-api-dev
      - helm/upgrade-helm-chart:
          namespace: hmcts-mock-api-dev
          update-repositories: false
          chart: ./helm_deploy/hmcts-common-platform-mock-api
          release-name: hmcts-common-platform-mock-api
          values: ./helm_deploy/hmcts-common-platform-mock-api/values.yaml
          values-to-override: image.tag=$CIRCLE_SHA1

  scan-docker-image:
    parameters:
      monitor:
        type: boolean
        default: false
    executor: snyk-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - build-temp-image
      - snyk/scan:
          token-variable: SNYK_TOKEN
          docker-image-name: mock:scan
          target-file: ./Dockerfile
          organization: "legal-aid-agency"
          severity-threshold: "critical"
          fail-on-issues: true
          no-output-timeout: 20m
          monitor-on-build: << parameters.monitor >>

  e2e-test-branch:
    executor: court-data-end-to-end-tests/e2e-test-executor
    steps:
      - court-data-end-to-end-tests/run-e2e-tests:
          e2e_current_image_var: MOCK_IMAGE
          e2e_current_image: ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/laa-crime-apps-team/hmcts-common-platform-mock-api:${CIRCLE_SHA1}
          e2e_branch: main # Change this to work against a fixed e2e test repo branch if needed (e.g. a seed data change)

  e2e-test-main:
    executor: court-data-end-to-end-tests/e2e-test-executor
    steps:
      - court-data-end-to-end-tests/run-e2e-tests

workflows:
  version: 2
  test_and_build_main:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      - build-and-push-app:
          requires:
            - test
      - scan-docker-image:
          name: scan-and-monitor-docker-image
          monitor: true
          requires:
            - test
      - e2e-test-main:
          requires:
            - build-and-push-app
      - install_on_live_cluster:
          requires:
          - build-and-push-app

  test_and_build_branch:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
      - scan-docker-image:
          name: scan-docker-image
          monitor: false
          requires:
            - test
      - build-and-push-app:
          requires:
            - test
      - e2e-test-branch:
          context: laa-court-data-e2e-tests
          requires:
            - build-and-push-app
      - hold_install_on_live:
          type: approval
          requires:
            - build-and-push-app
      - install_on_live_cluster:
          requires:
          - hold_install_on_live
