apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hmcts-common-platform-mock-api.fullname" . }}
  labels:
    {{- include "hmcts-common-platform-mock-api.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "hmcts-common-platform-mock-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "hmcts-common-platform-mock-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hmcts-common-platform-mock-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hmcts-mock-api-instance-output
                  key: url
            - name: SHARED_SECRET_KEY
              value: {{ .Values.common_platform_secret_key }}
            - name: ADMIN_USERNAME
              value: {{ .Values.admin_username }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.admin_password }}
            - name: SECRET_KEY_BASE
              value: {{ .Values.rails.secret_key_base }}
            - name: LAA_DEV_API_URL
              value: {{ .Values.laa.dev_api_url }}
            - name: LAA_DEV_OAUTH_URL
              value: {{ .Values.laa.dev_oauth_url }}
            - name: LAA_DEV_CLIENT_ID
              value: {{ .Values.laa.dev_client_id }}
            - name: LAA_DEV_CLIENT_SECRET
              value: {{ .Values.laa.dev_client_secret }}
            - name: LAA_TEST_API_URL
              value: {{ .Values.laa.test_api_url }}
            - name: LAA_TEST_OAUTH_URL
              value: {{ .Values.laa.test_oauth_url }}
            - name: LAA_TEST_CLIENT_ID
              value: {{ .Values.laa.test_client_id }}
            - name: LAA_TEST_CLIENT_SECRET
              value: {{ .Values.laa.test_client_secret }}
            - name: LAA_STAGE_API_URL
              value: {{ .Values.laa.stage_api_url }}
            - name: LAA_STAGE_OAUTH_URL
              value: {{ .Values.laa.stage_oauth_url }}
            - name: LAA_STAGE_CLIENT_ID
              value: {{ .Values.laa.stage_client_id }}
            - name: LAA_STAGE_CLIENT_SECRET
              value: {{ .Values.laa.stage_client_secret }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
