# frozen_string_literal: true

# set up schema matchers

RSpec.configure do |config|
  config.include JSON::SchemaMatchers

  schema_path = 'lib/schemas/'

  # Models
  config.json_schemas[:address] = "#{schema_path}/global/address.json"
  config.json_schemas[:allocation_decision] = "#{schema_path}/global/allocationDecision.json"
  config.json_schemas[:applicant_counsel] = "#{schema_path}/global/applicantCounsel.json"
  config.json_schemas[:associated_defence_organisation] = "#{schema_path}/global/associatedDefenceOrganisation.json"
  config.json_schemas[:associated_person] = "#{schema_path}/global/associatedPerson.json"
  config.json_schemas[:attendance_day] = "#{schema_path}/global/attendanceDay.json"
  config.json_schemas[:bail_status] = "#{schema_path}/global/bailStatus.json"
  config.json_schemas[:contact_number] = "#{schema_path}/global/contactNumber.json"
  config.json_schemas[:court_application] = "#{schema_path}/global/courtApplication.json"
  config.json_schemas[:court_application_outcome] = "#{schema_path}/global/courtApplicationOutcome.json"
  config.json_schemas[:court_application_outcome_type] = "#{schema_path}/global/courtApplicationOutcomeType.json"
  config.json_schemas[:court_application_party] = "#{schema_path}/global/courtApplicationParty.json"
  config.json_schemas[:court_application_party_counsel] = "#{schema_path}/global/courtApplicationPartyCounsel.json"
  config.json_schemas[:court_application_party_attendance] = "#{schema_path}/global/courtApplicationPartyAttendance.json"
  config.json_schemas[:court_application_payment] = "#{schema_path}/global/courtApplicationPayment.json"
  config.json_schemas[:court_application_respondent] = "#{schema_path}/global/courtApplicationRespondent.json"
  config.json_schemas[:court_application_response] = "#{schema_path}/global/courtApplicationResponse.json"
  config.json_schemas[:court_application_response_type] = "#{schema_path}/global/courtApplicationResponseType.json"
  config.json_schemas[:court_application_type] = "#{schema_path}/global/courtApplicationType.json"
  config.json_schemas[:court_centre] = "#{schema_path}/global/courtCentre.json"
  config.json_schemas[:court_indicated_sentence] = "#{schema_path}/global/courtIndicatedSentence.json"
  config.json_schemas[:cracked_ineffective_trial] = "#{schema_path}/global/crackedIneffectiveTrial.json"
  config.json_schemas[:custody_time_limit] = "#{schema_path}/global/custodyTimeLimit.json"
  config.json_schemas[:defence_counsel] = "#{schema_path}/global/defenceCounsel.json"
  config.json_schemas[:defence_organisation] = "#{schema_path}/global/defenceOrganisation.json"
  config.json_schemas[:defendant] = "#{schema_path}/global/defendant.json"
  config.json_schemas[:defendant_alias] = "#{schema_path}/global/defendantAlias.json"
  config.json_schemas[:defendant_attendance] = "#{schema_path}/global/defendantAttendance.json"
  config.json_schemas[:defendant_hearing_youth_marker] = "#{schema_path}/global/defendantHearingYouthMarker.json"
  config.json_schemas[:delegated_powers] = "#{schema_path}/global/delegatedPowers.json"
  config.json_schemas[:ethnicity] = "#{schema_path}/global/ethnicity.json"
  config.json_schemas[:hearing] = "#{schema_path}/global/hearing.json"
  config.json_schemas[:hearing_case_note] = "#{schema_path}/global/hearingCaseNote.json"
  config.json_schemas[:hearing_day] = "#{schema_path}/global/hearingDay.json"
  config.json_schemas[:hearing_type] = "#{schema_path}/global/hearingType.json"
  config.json_schemas[:indicated_plea] = "#{schema_path}/global/indicatedPlea.json"
  config.json_schemas[:judicial_result] = "#{schema_path}/global/judicialResult.json"
  config.json_schemas[:judicial_result_prompt] = "#{schema_path}/global/judicialResultPrompt.json"
  config.json_schemas[:judicial_result_prompt_duration_element] = "#{schema_path}/global/judicialResultPromptDurationElement.json"
  config.json_schemas[:judicial_role] = "#{schema_path}/global/judicialRole.json"
  config.json_schemas[:judicial_role_type] = "#{schema_path}/global/judicialRoleType.json"
  config.json_schemas[:jurors] = "#{schema_path}/global/jurors.json"
  config.json_schemas[:laa_reference] = "#{schema_path}/global/laaReference.json"
  config.json_schemas[:legal_entity_defendant] = "#{schema_path}/global/legalEntityDefendant.json"
  config.json_schemas[:lesser_or_alternative_offence] = "#{schema_path}/global/lesserOrAlternativeOffence.json"
  config.json_schemas[:linked_defendant] = "#{schema_path}/global/linkedDefendant.json"
  config.json_schemas[:marker] = "#{schema_path}/global/marker.json"
  config.json_schemas[:merged_prosecution_case] = "#{schema_path}/global/mergedProsecutionCase.json"
  config.json_schemas[:merged_prosecution_case_target] = "#{schema_path}/global/mergedProsecutionCaseTarget.json"
  config.json_schemas[:next_hearing] = "#{schema_path}/global/nextHearing.json"
  config.json_schemas[:next_hearing_defendant] = "#{schema_path}/global/nextHearingDefendant.json"
  config.json_schemas[:next_hearing_offence] = "#{schema_path}/global/nextHearingOffence.json"
  config.json_schemas[:next_hearing_prosecution_case] = "#{schema_path}/global/nextHearingProsecutionCase.json"
  config.json_schemas[:notified_plea] = "#{schema_path}/global/notifiedPlea.json"
  config.json_schemas[:offence] = "#{schema_path}/global/offence.json"
  config.json_schemas[:offence_facts] = "#{schema_path}/global/offenceFacts.json"
  config.json_schemas[:organisation] = "#{schema_path}/global/organisation.json"
  config.json_schemas[:person] = "#{schema_path}/global/person.json"
  config.json_schemas[:person_defendant] = "#{schema_path}/global/personDefendant.json"
  config.json_schemas[:plea] = "#{schema_path}/global/plea.json"
  config.json_schemas[:police_officer_in_case] = "#{schema_path}/global/policeOfficerInCase.json"
  config.json_schemas[:prosecuting_authority] = "#{schema_path}/global/prosecutingAuthority.json"
  config.json_schemas[:prosecution_case] = "#{schema_path}/global/prosecutionCase.json"
  config.json_schemas[:prosecution_case_identifier] = "#{schema_path}/global/prosecutionCaseIdentifier.json"
  config.json_schemas[:prosecution_counsel] = "#{schema_path}/global/prosecutionCounsel.json"
  config.json_schemas[:referral_reason] = "#{schema_path}/global/referralReason.json"
  config.json_schemas[:respondent_counsel] = "#{schema_path}/global/respondentCounsel.json"
  config.json_schemas[:verdict] = "#{schema_path}/global/verdict.json"
  config.json_schemas[:verdict_type] = "#{schema_path}/global/verdictType.json"

  # Search
  config.json_schemas[:defendant_name] = "#{schema_path}/global/search/defendantName.json"
  config.json_schemas[:defendant_summary] = "#{schema_path}/global/search/defendantSummary.json"
  config.json_schemas[:hearing_summary] = "#{schema_path}/global/search/hearingSummary.json"
  config.json_schemas[:offence_summary] = "#{schema_path}/global/search/offenceSummary.json"
  config.json_schemas[:prosecution_case_summary] = "#{schema_path}/global/search/prosecutionCaseSummary.json"

  # Responses
  config.json_schemas[:search_prosecution_case_response] = "#{schema_path}/api/search-prosecutionCaseResponse.json"
  config.json_schemas[:results_hearing_resulted_response] = "#{schema_path}/api/results.hearingResultedResponse.json"
end
