production:
  dev:
    api_url: <%= ENV['LAA_DEV_API_URL'] %>
    client_id: <%= ENV['LAA_DEV_CLIENT_ID'] %>
    client_secret: <%= ENV['LAA_DEV_CLIENT_SECRET'] %>
  test:
    api_url: <%= ENV['LAA_TEST_API_URL'] %>
    client_id: <%= ENV['LAA_TEST_CLIENT_ID'] %>
    client_secret: <%= ENV['LAA_TEST_CLIENT_SECRET'] %>
  stage:
    api_url: <%= ENV['LAA_STAGE_API_URL'] %>
    client_id: <%= ENV['LAA_STAGE_CLIENT_ID'] %>
    client_secret: <%= ENV['LAA_STAGE_CLIENT_SECRET'] %>
development:
  dev:
    api_url: <%= ENV['LAA_DEV_API_URL'] %>
    client_id: <%= ENV['LAA_DEV_CLIENT_ID'] %>
    client_secret: <%= ENV['LAA_DEV_CLIENT_SECRET'] %>
test:
  dev:
    api_url: <%= ENV['LAA_DEV_API_URL'] %>
    client_id: <%= ENV['LAA_DEV_CLIENT_ID'] %>
    client_secret: <%= ENV['LAA_DEV_CLIENT_SECRET'] %>
