# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#

CrackedIneffectiveTrial.create(code: "A", description: "Acceptable guilty plea(s) entered late to some or all charges / counts on the charge sheet, offered for the first tim
e by the defence", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "B", description: "Acceptable guilty plea(s) entered late to some or all charges / counts on the charge sheet, previously rejected by the prosecution", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "C", description: "Acceptable guilty plea(s) to alternative new charge (not previously on the charge sheet), first time offered by defence", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "D", description: "Acceptable guilty plea(s) to alternative new charge (not previously on the charge sheet, previously rejected by the prosecution", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "E", description: "Defendant bound over, now acceptable to prosecution - previously rejected by the prosecution", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "F", description: "Defendant bound over, acceptable to prosecution, offered for the first time by the defence", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "G", description: "Unable to proceed with trial because defendant incapable through alcohol/drugs", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "H", description: "Defendant deceased", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "I", description: "Prosecution end case: insufficient evidence", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "J", description: "Prosecution end case: witness absent / withdrawn", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "K", description: "Prosecution end case: public interest grounds", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "L", description: "Prosecution end case: adjournment refused", reason_type: "cracked")
CrackedIneffectiveTrial.create(code: "M1", description: "Prosecution offers no evidence not ready: served late notice of additional evidence on defence", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "M2", description: "Prosecution not ready: specify in comments", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "M3", description: "Prosecution failed to disclose unused material", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "N1", description: "Prosecution witness absent: police", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "N2", description: "Prosecution witness absent: professional / expert", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "N3", description: "Prosecution witness absent: other", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "O1", description: "Prosecution advocate engaged in another trial", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "O2", description: "Prosecution advocate failed to attend", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "P", description: "Prosecution increased time estimate - insufficient time for trial to start", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "Q1", description: "Defence not ready: disclosure problems", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "Q2", description: "Defence not ready: specify in comments (inc. no instructions)", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "Q3", description: "Defence asked for additional prosecution witness to attend", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "R", description: "Defence witness absent", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "S1", description: "Defendant absent - did not proceed in absence (judicial discretion)", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "S2", description: "Defendant ill or otherwise unfit to proceed", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "S3", description: "Defendant not produced by PECS", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "S4", description: "Defendant absent â€“ unable to proceed as Defendant not notified of place and time of hearing", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "T", description: "Defence increased time estimate â€“insufficient time for trial to start", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "U1", description: "Defence advocate engaged in other trial", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "U2", description: "Defence advocate failed to attend", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "V", description: "Defendant dismissed advocate", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "W1", description: "Another case over-ran", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "W2", description: "Judge / magistrate availability due to illness etc", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "W3", description: "Case not reached / insufficient cases drop out / Floater not reached", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "W4", description: "Equipment / accommodation failure/adverse weather", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "W5", description: "No interpreter available", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "X", description: "Insufficient jurors available", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "Y", description: "Outstanding cases / sent in a magistrates' court", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "Z", description: "Outstanding cases / sent in other Crown Court centre", reason_type: "ineffective")
CrackedIneffectiveTrial.create(code: "A", description: "Prosecution end case â€“ Prosecution discontinue case prior to trial date", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "B", description: "Prosecution not ready: prosecution not ready for trial, further preparation needed.", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "C", description: "Prosecution witness absent: prosecution witness not able to attend trial: Police witness. Counsel not available, Counsel ill.", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "D", description: "Prosecution witness not able to attend trial: Other witness.", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "E", description: "Defendant ill / deceased / unable to attend.", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "F", description: "Defence not ready: further preparation needed. Defence legal rep not available.", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "G", description: "Defence witness not able to attend trial", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "H", description: "Right to representation problems: Defendant dismissed legal representative.", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "I", description: "Lack of court time: Prosecution request increased time estimate", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "J", description: "Lack of court time: Defence request increased time estimate", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "K", description: "Lack of court time: Court vacate trial due to anticipated lack of court time", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "L", description: "Defendant changed plea to guilty: original charge", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "M", description: "Defendant changed plea to guilty: alternative charge", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "N", description: "Defendant bound over at PCMH", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "O", description: "Guilty plea with exceptional hardship pleaded.", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "P", description: "Accommodation / equipment failure/ adverse weather", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "Q", description: "Guilty plea at PCMH, trial fixed at PLY", reason_type: "vacated")
CrackedIneffectiveTrial.create(code: "Z", description: "Transfers out and errors (see page 3 of this guidance) â€“ Only these two", reason_type: "vacated")
